create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users (id) on delete cascade,
    email text not null unique,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists recovery_failed_attempts integer not null default 0;
alter table public.profiles add column if not exists recovery_locked_until timestamptz;

update public.profiles
set username = left(lower(regexp_replace(split_part(email, '@', 1), '[^a-z0-9_]+', '_', 'g')), 20)
where coalesce(username, '') = ''
  and coalesce(email, '') <> '';

create unique index if not exists idx_profiles_username on public.profiles (username)
where username is not null;

create table if not exists public.security_question_answers (
    user_id uuid not null references public.profiles (id) on delete cascade,
    question_order integer not null check (question_order between 1 and 3),
    question_key text not null,
    answer_salt text not null,
    answer_hash text not null,
    created_at timestamptz not null default timezone('utc', now()),
    primary key (user_id, question_order),
    unique (user_id, question_key)
);

create table if not exists public.assets (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
    name text not null,
    type text not null check (type in ('bank', 'cash', 'card', 'investment')),
    opening_balance numeric(14, 2) not null default 0,
    card_settlement_day integer,
    card_settlement_asset_id bigint,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
    date date not null,
    type text not null check (type in ('income', 'expense', 'investment')),
    asset_id bigint not null references public.assets (id),
    payment_method text not null default 'asset' check (payment_method in ('asset', 'card')),
    card_asset_id bigint references public.assets (id),
    settlement_date date,
    category text,
    description text,
    amount numeric(14, 2) not null check (amount > 0),
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.fixed_expenses (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
    category text not null,
    description text not null,
    amount numeric(14, 2) not null check (amount > 0),
    start_month text not null,
    end_month text not null,
    day_of_month integer not null default 1 check (day_of_month between 1 and 31),
    asset_id bigint references public.assets (id),
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.budgets (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
    category text not null,
    amount numeric(14, 2) not null check (amount > 0),
    created_at timestamptz not null default timezone('utc', now()),
    unique (user_id, category)
);

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
    type text not null check (type in ('expense', 'income', 'investment', 'fixed')),
    name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    unique (user_id, type, name)
);

create table if not exists public.investments (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
    asset_id bigint not null references public.assets (id),
    symbol text not null,
    name text,
    type text not null check (type in ('stock', 'crypto', 'etf', 'fund')),
    market text not null default 'MANUAL',
    currency text not null default 'KRW',
    quantity numeric(20, 8) not null check (quantity > 0),
    average_buy_price numeric(20, 8) not null check (average_buy_price > 0),
    current_price numeric(20, 8),
    fx_rate_krw numeric(20, 8) not null default 1,
    price_source text not null default 'manual',
    roi numeric(10, 4),
    last_updated timestamptz,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.investments
    add column if not exists market text not null default 'MANUAL';

alter table public.investments
    add column if not exists currency text not null default 'KRW';

alter table public.investments
    add column if not exists fx_rate_krw numeric(20, 8) not null default 1;

alter table public.investments
    add column if not exists price_source text not null default 'manual';

update public.investments
set market = case
        when type = 'crypto' then 'CRYPTO'
        when type = 'fund' then 'MANUAL'
        else coalesce(nullif(market, ''), 'MANUAL')
    end,
    currency = case
        when type = 'crypto' then 'USD'
        when type = 'fund' then 'KRW'
        else coalesce(nullif(currency, ''), 'KRW')
    end,
    fx_rate_krw = case
        when coalesce(fx_rate_krw, 0) > 0 then fx_rate_krw
        when currency = 'USD' then 1
        else 1
    end,
    price_source = coalesce(nullif(price_source, ''), case when type = 'fund' then 'manual' else 'yahoo' end);

create index if not exists idx_assets_user_id on public.assets (user_id);
create index if not exists idx_transactions_user_id_date on public.transactions (user_id, date desc);
create index if not exists idx_fixed_expenses_user_id on public.fixed_expenses (user_id);
create index if not exists idx_budgets_user_id on public.budgets (user_id);
create index if not exists idx_categories_user_id on public.categories (user_id);
create index if not exists idx_investments_user_id on public.investments (user_id);
create index if not exists idx_security_question_answers_user_id on public.security_question_answers (user_id);

create or replace function public.registration_slots_remaining()
returns integer
language sql
security definer
set search_path = public
as $$
    select greatest(50 - count(*), 0)::integer
    from public.profiles;
$$;

grant execute on function public.registration_slots_remaining() to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    slot_count integer;
    normalized_username text;
begin
    perform pg_advisory_xact_lock(20260315);

    normalized_username := lower(
        trim(
            coalesce(
                new.raw_user_meta_data ->> 'username',
                split_part(coalesce(new.email, ''), '@', 1)
            )
        )
    );

    if normalized_username = '' then
        raise exception '아이디가 비어 있습니다.';
    end if;

    if normalized_username !~ '^[a-z0-9_]{4,20}$' then
        raise exception '아이디는 영문 소문자, 숫자, 밑줄만 사용해서 4~20자로 입력해주세요.';
    end if;

    select count(*) into slot_count
    from public.profiles;

    if slot_count >= 50 then
        raise exception '회원가입 가능 인원이 가득 찼습니다.';
    end if;

    insert into public.profiles (id, email, username)
    values (
        new.id,
        coalesce(new.email, ''),
        normalized_username
    )
    on conflict (id) do update
    set email = excluded.email,
        username = excluded.username;

    insert into public.categories (user_id, type, name, sort_order, is_active)
    values
        (new.id, 'expense', '식비', 0, true),
        (new.id, 'expense', '교통', 1, true),
        (new.id, 'expense', '주거', 2, true),
        (new.id, 'expense', '통신', 3, true),
        (new.id, 'expense', '의료', 4, true),
        (new.id, 'expense', '할부', 5, true),
        (new.id, 'expense', '기타', 6, true),
        (new.id, 'income', '월급', 0, true),
        (new.id, 'income', '상여', 1, true),
        (new.id, 'income', '부수입', 2, true),
        (new.id, 'investment', '주식', 0, true),
        (new.id, 'investment', '코인', 1, true),
        (new.id, 'investment', '예적금', 2, true),
        (new.id, 'fixed', '고정지출', 0, true)
    on conflict (user_id, type, name) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.validate_asset_row()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    settlement_asset public.assets;
begin
    if new.type <> 'card' then
        new.card_settlement_day := null;
        new.card_settlement_asset_id := null;
        return new;
    end if;

    if new.card_settlement_day is null or new.card_settlement_day < 1 or new.card_settlement_day > 31 then
        raise exception '카드 자산은 결제일(1~31)이 필요합니다.';
    end if;

    if new.card_settlement_asset_id is null then
        raise exception '카드 자산은 결제 통장 설정이 필요합니다.';
    end if;

    select *
    into settlement_asset
    from public.assets
    where id = new.card_settlement_asset_id
      and user_id = new.user_id;

    if settlement_asset.id is null then
        raise exception '카드 결제 통장 자산을 찾을 수 없습니다.';
    end if;

    if settlement_asset.type not in ('cash', 'bank') then
        raise exception '카드 결제 통장은 은행/현금 자산이어야 합니다.';
    end if;

    if new.id is not null and settlement_asset.id = new.id then
        raise exception '카드 결제 통장은 자기 자신으로 설정할 수 없습니다.';
    end if;

    return new;
end;
$$;

drop trigger if exists validate_asset_row on public.assets;
create trigger validate_asset_row
before insert or update on public.assets
for each row execute function public.validate_asset_row();

create or replace function public.validate_transaction_row()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    settlement_asset public.assets;
    card_asset public.assets;
begin
    select *
    into settlement_asset
    from public.assets
    where id = new.asset_id
      and user_id = new.user_id;

    if settlement_asset.id is null then
        raise exception '결제/정산 자산을 찾을 수 없습니다.';
    end if;

    if new.payment_method = 'card' then
        if new.type = 'income' then
            raise exception '수입은 카드 결제 방식으로 저장할 수 없습니다.';
        end if;

        if new.card_asset_id is null then
            raise exception '카드 자산을 선택해주세요.';
        end if;

        select *
        into card_asset
        from public.assets
        where id = new.card_asset_id
          and user_id = new.user_id;

        if card_asset.id is null then
            raise exception '카드 자산을 찾을 수 없습니다.';
        end if;

        if card_asset.type <> 'card' then
            raise exception '카드 결제에는 카드 자산이 필요합니다.';
        end if;

        if settlement_asset.type not in ('cash', 'bank') then
            raise exception '카드 정산 자산은 은행/현금 자산이어야 합니다.';
        end if;

        if new.settlement_date is null then
            raise exception '카드 결제는 결제일이 필요합니다.';
        end if;
    else
        new.card_asset_id := null;
        new.settlement_date := null;
    end if;

    return new;
end;
$$;

drop trigger if exists validate_transaction_row on public.transactions;
create trigger validate_transaction_row
before insert or update on public.transactions
for each row execute function public.validate_transaction_row();

create or replace function public.validate_fixed_expense_row()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    linked_asset public.assets;
begin
    if new.asset_id is null then
        return new;
    end if;

    select *
    into linked_asset
    from public.assets
    where id = new.asset_id
      and user_id = new.user_id;

    if linked_asset.id is null then
        raise exception '고정지출 자산을 찾을 수 없습니다.';
    end if;

    return new;
end;
$$;

drop trigger if exists validate_fixed_expense_row on public.fixed_expenses;
create trigger validate_fixed_expense_row
before insert or update on public.fixed_expenses
for each row execute function public.validate_fixed_expense_row();

create or replace function public.validate_investment_row()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    linked_asset public.assets;
begin
    select *
    into linked_asset
    from public.assets
    where id = new.asset_id
      and user_id = new.user_id;

    if linked_asset.id is null then
        raise exception '연결 자산을 찾을 수 없습니다.';
    end if;

    return new;
end;
$$;

drop trigger if exists validate_investment_row on public.investments;
create trigger validate_investment_row
before insert or update on public.investments
for each row execute function public.validate_investment_row();

create or replace function public.delete_asset_cascade(p_asset_id bigint, p_force boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    uid uuid := auth.uid();
    target_asset public.assets;
    tx_count integer;
    fixed_count integer;
    investment_count integer;
    card_cfg_count integer;
    latest_tx record;
    tx_hint text := '';
begin
    if uid is null then
        raise exception '로그인이 필요합니다.';
    end if;

    select *
    into target_asset
    from public.assets
    where id = p_asset_id
      and user_id = uid;

    if target_asset.id is null then
        raise exception 'Asset not found';
    end if;

    select count(*) into tx_count
    from public.transactions
    where user_id = uid
      and (asset_id = p_asset_id or card_asset_id = p_asset_id);

    select count(*) into fixed_count
    from public.fixed_expenses
    where user_id = uid
      and asset_id = p_asset_id;

    select count(*) into investment_count
    from public.investments
    where user_id = uid
      and asset_id = p_asset_id;

    select count(*) into card_cfg_count
    from public.assets
    where user_id = uid
      and card_settlement_asset_id = p_asset_id;

    if (tx_count + fixed_count + investment_count + card_cfg_count) > 0 and not p_force then
        select date, type, description, amount
        into latest_tx
        from public.transactions
        where user_id = uid
          and (asset_id = p_asset_id or card_asset_id = p_asset_id)
        order by date desc, id desc
        limit 1;

        if latest_tx.date is not null then
            tx_hint := format(
                ' | 예시 거래: %s %s %s %s원',
                latest_tx.date,
                case latest_tx.type when 'income' then '수입' when 'investment' then '투자' else '지출' end,
                coalesce(latest_tx.description, '-'),
                to_char(latest_tx.amount, 'FM999,999,999,990')
            );
        end if;

        raise exception '연결된 데이터가 있어 삭제할 수 없습니다. 거래 %건, 고정지출 %건, 투자 %건, 카드결제설정 %건%s',
            tx_count, fixed_count, investment_count, card_cfg_count, tx_hint;
    end if;

    if p_force then
        delete from public.transactions
        where user_id = uid
          and (asset_id = p_asset_id or card_asset_id = p_asset_id);

        delete from public.fixed_expenses
        where user_id = uid
          and asset_id = p_asset_id;

        delete from public.investments
        where user_id = uid
          and asset_id = p_asset_id;

        update public.assets
        set card_settlement_asset_id = null
        where user_id = uid
          and card_settlement_asset_id = p_asset_id;
    end if;

    delete from public.assets
    where id = p_asset_id
      and user_id = uid;

    return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.delete_asset_cascade(bigint, boolean) to authenticated;

create or replace function public.clear_user_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    uid uuid := auth.uid();
begin
    if uid is null then
        raise exception '로그인이 필요합니다.';
    end if;

    delete from public.transactions where user_id = uid;
    delete from public.fixed_expenses where user_id = uid;
    delete from public.investments where user_id = uid;
    delete from public.budgets where user_id = uid;
    delete from public.categories where user_id = uid;
    delete from public.assets where user_id = uid;
end;
$$;

grant execute on function public.clear_user_data() to authenticated;

alter table public.profiles enable row level security;
alter table public.security_question_answers enable row level security;
alter table public.assets enable row level security;
alter table public.transactions enable row level security;
alter table public.fixed_expenses enable row level security;
alter table public.budgets enable row level security;
alter table public.categories enable row level security;
alter table public.investments enable row level security;

revoke all on table public.security_question_answers from anon, authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated
using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;

drop policy if exists "assets_select_own" on public.assets;
create policy "assets_select_own" on public.assets
for select to authenticated
using (user_id = auth.uid());

drop policy if exists "assets_insert_own" on public.assets;
create policy "assets_insert_own" on public.assets
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "assets_update_own" on public.assets;
create policy "assets_update_own" on public.assets
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "transactions_all_own" on public.transactions;
create policy "transactions_all_own" on public.transactions
for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "fixed_expenses_all_own" on public.fixed_expenses;
create policy "fixed_expenses_all_own" on public.fixed_expenses
for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "budgets_all_own" on public.budgets;
create policy "budgets_all_own" on public.budgets
for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "categories_all_own" on public.categories;
create policy "categories_all_own" on public.categories
for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "investments_all_own" on public.investments;
create policy "investments_all_own" on public.investments
for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());
